title: Вестник СВФУ
description: Научный журнал, периодическое издание, основан в 2004 г. Учредитель и издатель - Северо-Восточный федеральный университет имени М.К. Аммосова.
show_downloads: true
google_analytics: G-LMS9R7KWBB
theme: jekyll-theme-slate
